version: '3.8'
services:
  # PostgreSQL
  postgres:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network

  
  # Nginx
  # nginx:
  #   image: nginx:latest
  #   container_name: my_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/html:/usr/share/nginx/html
  #   restart: always
  #   networks:
  #     - my_network
  # MariaDB
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:${MYSQL_DATA_PATH}
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data: 
  mariadb_data: