version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:${MYSQL_DATA_PATH}
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mariadb_data: