version: '3.8'
services:
  # Node.js
  
  # Nginx
  # nginx:
  #   image: nginx:latest
  #   container_name: my_nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx/conf.d
  #     - ./nginx/html:/usr/share/nginx/html
  #   restart: always
  #   networks:
  #     - my_network
  # MariaDB
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb_data:${MYSQL_DATA_PATH}
    restart: always
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mariadb_data: